App_login/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Login_App.urls'))
]

Login_App/urls.py
from django.urls import path
from Login_App import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

app_name= 'Login_App'
urlpatterns = [
    path('', views.home_page, name="home"),
    path('register/', views.register, name="register"),
    path('login/', views.login_page, name="login"),
    path('user_login/', views.user_login, name="user_login"),
    path('logout/', views.user_logout, name="logout")
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Login_App/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    facebook_id = models.URLField(max_length = 200, blank = True)
    profile_pic = models.ImageField(upload_to = 'profile_pics', blank=True)

    def __str__(self):
        return self.user.username

Login_App/forms.py
from django import forms
from django.contrib.auth.models import User
from Login_App.models import UserInfo 

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserInfoForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        fields = ('facebook_id', 'profile_pic')

Login_App/views.py
from django.shortcuts import render
from Login_App.forms import UserForm, UserInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib.auth.models import User
from Login_App.models import UserInfo

# Create your views here.
def home_page(request):
    diction = {}
    if request.user.is_authenticated:
        current_user = request.user
        user_id = current_user.id
        user_info = User.objects.get(pk = user_id)
        # user_more_info = UserInfo.objects.get(user__pk=user_id)
        diction = {'user_info':user_info}
    return render(request, 'Login_App/index.html', context=diction)

def login_page(request):
    diction = {}
    return render(request, "Login_App/login.html", context=diction)

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username, password = password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('Login_App:home'))
            else:
                return HttpResponse('User is not active!')
        
        else:
            return HttpResponse('Login details are wrong!')
    else:
        return HttpResponseRedirect('Login_App:login')
    

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("Login_App:home"))
    

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        user_info_form = UserInfoForm(data=request.POST)

        if user_form.is_valid() and user_info_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            user_info = user_info_form.save(commit = False)
            user_info.user = user

            if 'profile_pic' in request.FILES:
                user_info.profile_pic = request.FILES['profile_pic']
            
            user_info.save()
            registered = True
    else:
        user_form = UserForm()
        user_info_form = UserInfoForm()

    dict = {'user_form':user_form, 'user_info_form':user_info_form, 'registered':registered}
    return render(request, 'Login_App/register.html', context = dict)

templates/Login_App/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Authentication App</title>
    {% comment %} BOOTSTRAP (CSS) {% endcomment %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% comment %} BOOTSTRAP (JS) {% endcomment %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" defer>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-dark">
        <div class="container">
          <a class="navbar-brand text-light" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse ms-auto" id="navbarNavAltMarkup">
            {% if user.is_authenticated %}
            <div class="navbar-nav ">
              <a class="nav-link text-light" href="{% url 'Login_App:home' %}">Home</a>
            </div>
            <div class="navbar-nav ">
              <a class="nav-link text-light" href="{% url 'Login_App:logout' %}">Logout</a>
            </div>
            {% else %}
            <div class="navbar-nav ">
              <a class="nav-link text-light" href="{% url 'Login_App:register' %}">Register</a>
            </div>
            <div class="navbar-nav ">
              <a class="nav-link text-light" href="{% url 'Login_App:login' %}">Login</a>
            </div>
            {% endif %}
            
          </div>
        </div>
      </nav>
      <div class="container pt-5">
        {% block body_block %}
    
        {% endblock  %}
      </div>
   
</body>
</html>

templates/Login_App/index.html
{% extends "Login_App/base.html" %}

{% block body_block %}
    {% if user.is_authenticated %}
    <p>{{ user_info.username }}</p>
    {% else %}
    <p>Simple auth app</p>
    {% endif %}
    
{% endblock  %}

templates/Login_App/login.html
{% extends "Login_App/base.html" %}

{% block body_block %}
<h2>Please Login:</h2>
<form action="{% url 'Login_App:user_login' %}" method="POST">
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter username" class='form-control'>
    <label for="password">Password</label>
    <input type="password" name="password" placeholder="Enter password" class='form-control'>
    {% csrf_token %}
    <br>
    <input type="submit"  name= "login" value="Login">
</form>
{% endblock  %}

templates/Login_App/register.html
{% extends "Login_App/base.html" %}
{% load static %}

{% block body_block %}
{%if registered %}
<div class="alert alert-success">Congratulations. Registration successful :D</div>
    {% else %}
    <form method="POST" enctype="multipart/form-data">
        {{ user_form.as_p }}
        {{ user_info_form.as_p }}
        {% csrf_token %}
        <input type="submit" name="submit" value="Register" class="btn btn-primary btn-sm">
    </form>
{% endif %}
{% endblock  %}